// Data-only teaching diagrams. No final answer is supplied by these hints.
function teachingVisual(task,step,level){
  const f=n=>String(n).replace('.',','),d=task.data;
  if(step===-1){const p=Motion.preparation(task);return {kind:'cards',title:level===3?'Ein Feld als Beispiel':'Angaben zuordnen',items:p.cells.map((c,i)=>({label:c.label,value:level===3&&i===0?(c.unit==='clock'?c.expected+' Uhr':f(c.expected)+' '+c.unit):c.unit==='clock'?'Stunde : Minute':c.unit==='km'?'Abstand oder Strecke → km':c.unit==='km/h'?'Strecke pro Zeit → km/h':'Zeit seit Beginn → min'})),note:p.layout==='pairs'?'Oben: Zeiten. Darunter: jeweils die Position zu genau dieser Zeit.':'Ein Abstand zu einem Ort ist eine Position. Eine zusätzlich zurückgelegte Strecke beschreibt eine Änderung.'};}
  if(step===0){
    if(task.type==='inferred'||task.type.startsWith('direct_'))return {kind:'cards',title:'Die Einheit hilft beim Finden',items:[{label:'Position',value:'km'},{label:'Zeitdauer',value:'min oder h'},{label:'Geschwindigkeit',value:'km/h'}],note:level===3?'Suche im Text die Zahl unmittelbar vor km/h.':'Welche Angabe beschreibt, wie viele Kilometer in einer Stunde zurückgelegt werden?'};
    if(task.type==='table')return {kind:'changes',title:'Von der ersten zur zweiten Beobachtung',rows:[{label:'Zeit',from:f(d.firstT*60)+' min',to:f((d.firstT+d.elapsed)*60)+' min',change:level===1?'Wie viel Zeit vergeht?':level===2?`${f((d.firstT+d.elapsed)*60)} − ${f(d.firstT*60)} = ? min`:`${f(d.elapsed*60)} min = ${f(d.elapsed)} h`},{label:'Position',from:f(d.s0+d.v*d.firstT)+' km',to:f(d.s0+d.v*(d.firstT+d.elapsed))+' km',change:level===1?'Um wie viel wächst der Abstand?':level===2?`${f(d.s0+d.v*(d.firstT+d.elapsed))} − ${f(d.s0+d.v*d.firstT)} = ? km`:`Änderung der Position: ${f(d.v*d.elapsed)} km`}],note:level===3?`Geschwindigkeit: ${f(d.v*d.elapsed)} km : ${f(d.elapsed)} h = ? km/h`:'Die Bewegung führt weiter vom Bezugspunkt weg. Die Positionsänderung ist hier die zurückgelegte Strecke.'};
    if(task.type==='clock')return {kind:'changes',title:'Wie lange dauert die Beobachtung?',rows:[{label:'Uhrzeit',from:Motion.preparation(task).cells[1].expected+' Uhr',to:Motion.preparation(task).cells[2].expected+' Uhr',change:level===3?`${f(d.elapsed*60)} min = ${f(d.elapsed)} h`:'Ende − Beginn = vergangene Zeit'}],note:level===3?`Weitere Strecke: ${f(d.v*d.elapsed)} km. Geschwindigkeit: ${f(d.v*d.elapsed)} km : ${f(d.elapsed)} h = ? km/h`:`In dieser Zeit werden weitere ${f(d.v*d.elapsed)} km zurückgelegt. Der Anfangsabstand zählt nicht dazu.`};
    return {kind:'journey',title:'Die zusätzliche Strecke zählt',from:`Beginn: ${f(d.s0)} km vom Bezugspunkt`,to:'Ende der Beobachtung',travel:`Weitere ${f(d.v*d.elapsed)} km`,time:level===3?`${f(d.elapsed*60)} min : 60 = ${f(d.elapsed)} h`:`Dauer: ${f(d.elapsed*60)} min`,note:level===3?`Geschwindigkeit: ${f(d.v*d.elapsed)} km : ${f(d.elapsed)} h = ? km/h`:'Teile die zusätzliche Strecke durch die dafür benötigte Zeit.'};
  }
  if(step===1){
    if(task.type==='table'||task.type==='inferred')return {kind:'journey',title:'Vom späteren Ort zurück zum Anfang',from:'Beginn: s₀ = ?',to:`Später: ${f(d.s0+d.v*d.firstT)} km`,travel:level===3?`Seit Beginn zurückgelegt: ${f(d.v*d.firstT)} km`:'Seit Beginn zurückgelegt: v · t',time:`Bis zu dieser Beobachtung: ${f(d.firstT*60)} min${level>=2?' = '+f(d.firstT)+' h':''}`,note:level===3?`Anfangsposition: ${f(d.s0+d.v*d.firstT)} km − ${f(d.v*d.firstT)} km = ? km`:'Gehe vom bekannten späteren Abstand die seit Beginn zurückgelegte Strecke zurück.',back:true};
    return {kind:'cards',title:'Der richtige Moment',items:[{label:'Beginn der Zeitmessung',value:'Anfangsposition s₀ = ?'},{label:'Später',value:'Ein späterer Abstand ist nicht s₀.'}],note:task.type==='direct_zero'?'Beim Vorbeikommen befinden sich Person oder Fahrzeug direkt am gewählten Bezugspunkt.':'Suche im Text den Abstand beim Beginn der Zeitmessung.'};
  }
  if(step===2)return {kind:'formula',title:level===3?'Die Größen einzeln zuordnen':'Bausteine der Bewegungsformel',items:[{label:'Geschwindigkeit v',value:level===3?f(task.v)+' km/h':'Einheit: km/h'},{label:'Zeit t',value:'bleibt als Variable t'},{label:'Anfangsposition s₀',value:level===3?f(task.s0)+' km':'Einheit: km'}],note:level===1?'s(t) = v · t + s₀':level===2?'Geschwindigkeit × Zeit ergibt eine Strecke. Dazu kommt die Anfangsposition.':'Setze die beiden bekannten Größen selbst an die passenden Stellen. Die Zeit bleibt variabel.'};
  return {kind:'journey',title:'Anfangsabstand und weitere Strecke',from:`Anfangsposition: ${f(task.s0)} km`,to:'Gesuchte Position: ?',travel:level>=2?`${f(task.v)} km/h · ${level===3?f(task.targetT)+' h':'t'}`:'Zusätzliche Strecke: v · t',time:`Gefragte Zeit: ${f(task.targetT*60)} min${level>=2?' = '+f(task.targetT)+' h':''}`,note:level===3?`${f(task.v)} km/h · ${f(task.targetT)} h + ${f(task.s0)} km = ? km`:'Die Position setzt sich aus dem Anfangsabstand und der seitdem zurückgelegten Strecke zusammen.'};
}
function renderTeachingVisual(data){
  const box=el('figure',undefined,'teaching-visual '+data.kind);box.append(el('figcaption',data.title));
  if(data.kind==='changes')for(const r of data.rows){const row=el('div',undefined,'change-row');row.append(el('span',r.label,'change-label'),el('span',r.from,'change-value'),el('span','→','change-arrow'),el('span',r.to,'change-value'),el('span',r.change,'change-explain'));box.append(row);}
  else if(data.kind==='journey'){
    const path=el('div',undefined,'journey-track');path.append(el('span',data.from,'journey-point'),el('span',data.back?'←':'→','journey-arrow'),el('span',data.to,'journey-point'));box.append(path,el('p',data.travel,'journey-travel'),el('p',data.time,'journey-time'));
  }else{const cards=el('div',undefined,'visual-cards');data.items.forEach(item=>{const card=el('div',undefined,'visual-card');card.append(el('span',item.label),el('strong',item.value));cards.append(card);});box.append(cards);}
  box.append(el('p',data.note,'visual-note'));return box;
}
