const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const raw=fs.readFileSync(path.join(__dirname,'../dynamot-labor.html'),'utf8').replace('init();frame=requestAnimationFrame(tick);','window.labTest={get view(){return view},get state(){return state},get pending(){return pending},render};init();frame=requestAnimationFrame(tick);');
const server=http.createServer((q,r)=>r.end(raw.replace('<body>','<body><textarea id="e1_text_input"></textarea>')));
const dist=(a,b)=>Math.hypot(...a.map((v,i)=>v-b[i]));
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});try{for(const width of [1024,1180])for(const edulo of [false,true]){const page=await browser.newPage({viewport:{width,height:width===1024?668:720},hasTouch:true});await page.goto(`http://127.0.0.1:${server.address().port}/?${edulo?'edulo=1':''}`);await page.waitForFunction(()=>window.labTest?.view);const cdp=await page.context().newCDPSession(page),box=await page.locator('canvas').boundingBox(),cx=box.x+box.width*.5,cy=box.y+box.height*.55;
 const cam=()=>page.evaluate(()=>labTest.view.getViewState()),send=(type,points)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points.map(([x,y],id)=>({x,y,id,radiusX:2,radiusY:2,force:1}))});
 async function two(dx,dy,spread){await send('touchStart',[[cx-35,cy],[cx+35,cy]]);for(let i=1;i<=8;i++)await send('touchMove',[[cx-35+dx*i/8-spread*i/8,cy+dy*i/8],[cx+35+dx*i/8+spread*i/8,cy+dy*i/8]]);await send('touchEnd',[]);}
 let a=await cam();await two(0,0,22);let b=await cam();assert(dist(b.position,b.target)<dist(a.position,a.target),'pinch zoom');
 for(const [dx,dy]of [[45,0],[0,35]]){a=await cam();await two(dx,dy,0);b=await cam();assert(dist(a.target,b.target)>.1,'pan target');assert(Math.abs(dist(a.position,a.target)-dist(b.position,b.target))<.1,'pan distance');}
 a=await cam();await two(-25,-20,10);b=await cam();assert(dist(a.target,b.target)>.1);assert(dist(b.position,b.target)<dist(a.position,a.target));
 // Two-to-one transition uses the remaining finger's current position.
 await send('touchStart',[[cx-30,cy],[cx+30,cy]]);await send('touchMove',[[cx-20,cy+10],[cx+40,cy+10]]);a=await cam();await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[{x:cx+40,y:cy+10,id:1}]});await send('touchMove',[[cx-20,cy+10]]);b=await cam();assert(dist(a.position,b.position)<1e-6,'no transition jump');await send('touchMove',[[cx-5,cy+10]]);await send('touchEnd',[]);b=await cam();assert(dist(a.position,b.position)>.1,'one-finger orbit');assert(dist(a.target,b.target)<1e-6,JSON.stringify({a,b}));
 await send('touchStart',[[cx-20,cy],[cx+20,cy]]);await send('touchCancel',[]);assert.equal(await page.evaluate(()=>labTest.pending),null);assert.equal(await page.locator('.device-panel').isVisible(),false);assert.equal(await page.evaluate(()=>scrollY),0);
 await page.locator('.slot-target:visible').first().tap();assert(await page.locator('.device-panel').isVisible(),'fresh tap directly after cancel');await page.locator('[data-action=close-device]').tap();
 const saved=await cam();const e1=await page.locator('#e1_text_input').inputValue();
 if(edulo){const state=JSON.parse(Buffer.from(e1.slice(9),'base64').toString());assert(dist(state.camera.target,saved.target)<1e-6);await page.route('**/*',route=>route.fulfill({contentType:'text/html',body:raw.replace('<body>',`<body><textarea id="e1_text_input">${e1}</textarea>`)}));}
 await page.reload();await page.waitForFunction(()=>window.labTest?.view);b=await cam();assert(dist(saved.target,b.target)<1e-6);assert(dist(saved.position,b.position)<1e-6);
 await page.locator('.slot-target:visible').first().tap();assert(await page.locator('.device-panel').isVisible(),'tap after gesture');await page.close();console.log({width,edulo,passed:true});}}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
