const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const raw=fs.readFileSync(path.join(__dirname,'../dynamot-labor.html'),'utf8');
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html;charset=utf-8');const u=new URL(req.url,'http://local');if(u.pathname==='/app')return res.end(raw);const mode=u.searchParams.get('mode'),mixed=mode==='mixed';res.end(`<style>textarea,input,.inputcontainer,#e1,#e2{display:block!important}</style><body class="${mode==='class'?'editor':''}"><script>window.events=0;${mode==='widget'?'window.widget={isEditor:true};':''}document.addEventListener('input',()=>events++);document.addEventListener('change',()=>events++);</script><section id="e1"><div class="inputcontainer"><textarea id="e1_text_input" style="height:300px"></textarea>${mixed?'<input id="other" value="untouched">':''}</div></section><section id="e2">${Array.from({length:20},(_,i)=>`<div class="inputcontainer"><input id="e2_cloze_text_input_${i+1}"></div>`).join('')}</section><input id="unrelated" value="keep"><iframe src="/app?edulo=1${mode==='show'?'&SHOW_FIELDS=1':''}" style="width:1180px;height:720px"></iframe>`);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({channel:'msedge',headless:true});for(const mode of ['learn','mixed','show','class','widget','query']){const page=await browser.newPage();await page.goto(`http://127.0.0.1:${server.address().port}/?mode=${mode}${mode==='query'?'&editor=1':''}`);const frame=page.frames().find(f=>f.url().includes('/app'));await frame.waitForFunction(()=>document.querySelector('#energyLab')?.energyLab?.getPersistenceStatus().ready);await frame.waitForFunction(()=>document.querySelector('.learn-storage'));
 const editor=['class','widget','query'].includes(mode),visible=editor||mode==='show';
 await page.waitForFunction(({editor})=>editor||document.querySelector('#e2_cloze_text_input_20').value==='0',{editor});
 assert.equal(await page.locator('#e1_text_input').isVisible(),visible,mode+' E1');assert.equal(await page.locator('#e2_cloze_text_input_1').isVisible(),visible,mode+' E2');assert(await page.locator('#unrelated').isVisible());assert(await page.locator('iframe').isVisible());
 if(mode==='mixed'){assert(await page.locator('#other').isVisible());assert(await page.locator('#e1').isVisible());}
 if(editor){assert.equal(await page.locator('#e1_text_input').inputValue(),'');assert.equal(await page.evaluate(()=>events),0);}else{assert((await page.locator('#e1_text_input').inputValue()).startsWith('DYNAMOT1:'));await frame.evaluate(()=>document.querySelector('#energyLab').energyLab.setTaskState('visibility-test',{text:'Größe bleibt erhalten',value:17}));assert((await page.evaluate(()=>events))>0);await frame.goto(frame.url());await frame.waitForFunction(()=>document.querySelector('#energyLab')?.energyLab?.getPersistenceStatus().ready);assert.deepEqual(await frame.evaluate(()=>document.querySelector('#energyLab').energyLab.getTaskState('visibility-test')),{text:'Größe bleibt erhalten',value:17});
 // A runtime switch to editor restores original inline styles and containers.
 if(mode==='learn'){await page.evaluate(()=>document.body.classList.add('editor'));await frame.evaluate(()=>document.querySelector('#energyLab').energyLab.setTaskState('visibility-test',{value:18}));assert(await page.locator('#e1_text_input').isVisible());assert(await page.locator('#e2_cloze_text_input_1').isVisible());assert.equal(await page.locator('#e1').evaluate(e=>e.style.getPropertyValue('display')),'');}}
 await page.close();console.log(mode+' passed');}console.log('Edulo fields: CSS override, scoped wrappers, editor modes, SHOW_FIELDS, events and roundtrip passed.');}finally{await browser?.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
