const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const file=path.join(__dirname,'../Anteile berechnen 2.html'),raw=fs.readFileSync(file,'utf8');
const html=raw.replace(/connect\(\);\s*\}\)\(\);/,`Object.assign(window,{fresh,render,save,POOL,SCENES,expected,rationalText,partitionOptions,pointRequirements,parseState,encodeState,chooseTask,taskKey,numberKey,ensureSelection,completeSelection,newTask});Object.defineProperty(window,'state',{configurable:true,get:()=>state,set:v=>state=v});connect();})();`);
const fields='<div id="e1"><textarea id="e1_text_input"></textarea></div><div id="e2">'+Array.from({length:20},(_,i)=>`<input id="e2_cloze_text_input_${i+1}">`).join('')+'</div>';
let initial='',browser;
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html;charset=utf-8');res.end(req.url.startsWith('/host')?fields.replace('</textarea>',initial+'</textarea>')+'<script>document.querySelector("textarea").addEventListener("input",e=>{e.target.value=e.target.value.replace(/"/g,"„")});</script><iframe src="/app?edulo=1"></iframe>':req.url.startsWith('/inline')?'<body class="editor">'+fields+'<div id="slot"></div></body>':html)});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1000,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);
 async function seed(mode='divide',scene='cola'){await page.evaluate(({mode,scene})=>{state=fresh();state.mode=mode;const task=POOL.find(t=>t.scene===scene&&t.n===3&&t.d===4)||POOL.find(t=>t.scene===scene);state.active={task,mode,route:mode==='choice'?null:mode,stage:'selectUnit',unitChoice:'',parts:1,copies:1,selected:[],input:'',attempts:[],hadError:false,work:[],started:new Date().toISOString()};render();save();},{mode,scene});}
 async function solve(target=page,route='divide',reload=false){for(let i=0;i<10;i++){const a=await target.evaluate(()=>state.active);if(a.stage==='done')return;if(a.stage==='selectUnit'){await target.locator('#unitSelect').selectOption(await target.evaluate(()=>SCENES.find(s=>s.id===state.active.task.scene).unit));await target.locator('#checkUnit').click();}else if(a.stage==='route')await target.locator(`[data-route=${route}]`).click();else if(['divideParts','copies','multiplyParts'].includes(a.stage)){await target.locator('#range').fill(String(await target.evaluate(()=>state.active.stage==='copies'?state.active.task.n:partitionOptions(state.active.task).indexOf(state.active.task.d)+1)));await target.locator('#checkRange').click();}else if(a.stage==='mark'){for(let j=0;j<a.task.n;j++)if(!a.selected.includes(j))await target.locator(`[data-part="${j}"]`).press('Enter');await target.locator('#checkMark').click();}else{await target.locator('#answer').fill(await target.evaluate(()=>rationalText(expected(state.active))));await target.locator('#answerForm button').click();}if(reload)await page.reload();}assert.fail('unfinished');}
 const report=await page.evaluate(()=>({count:POOL.length,scenes:SCENES.length,bad:POOL.filter(t=>{const s=SCENES.find(s=>s.id===t.scene);return t.n<2||!Number.isInteger(t.whole/t.d)||Number.isInteger(t.whole/s.conversion.factor*t.n/t.d)||s.conversion.options.filter(u=>u===s.unit).length!==1}).length}));assert.equal(report.bad,0);assert.equal(report.scenes,17);assert.ok(report.count>460);
 for(const [mode,route] of [['divide','divide'],['multiply','multiply'],['choice','divide'],['choice','multiply']]){await seed(mode);assert.equal(await page.locator('#stepTip').isVisible(),false);await solve(page,route,true);const a=await page.evaluate(()=>state);assert.equal(a.history[0].correct,true);assert.equal(a.history[0].attempts.length,mode==='choice'?4:6);assert.equal(a.history[0].work.length,3);assert.equal(await page.locator('[data-completed-stage="convert"]').count(),1);assert.equal(await page.locator('#pictureWork [data-equation]').count(),2);assert.equal(await page.locator('#flow').isVisible(),true);}
 await seed();await page.locator('#unitSelect').selectOption('g');await page.reload();assert.equal(await page.locator('#unitSelect').inputValue(),'g');await page.locator('#checkUnit').click();assert.equal(await page.locator('#stepTip').isVisible(),true);await page.locator('#unitSelect').selectOption('ml');await page.locator('#checkUnit').click();await page.locator('#answer').fill('1000/1');await page.locator('#answerForm button').click();assert.equal(await page.evaluate(()=>state.active.stage),'convert');await page.locator('#answer').fill('100');await page.reload();assert.equal(await page.locator('#answer').inputValue(),'100');await page.locator('#answerForm button').click();await solve();assert.equal(await page.evaluate(()=>state.history[0].correct),false);
 for(const width of [1000,390,320]){await page.setViewportSize({width,height:1100});for(const scene of await page.evaluate(()=>SCENES.map(s=>s.id))){await seed('multiply',scene);await solve();assert.ok(await page.locator('.object > svg').count()>=2);assert.equal(await page.locator('svg rect rect,svg path path').count(),0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,scene+' '+width);}await page.screenshot({path:path.join(require('node:os').tmpdir(),'anteile-units-'+width+'.png'),fullPage:true});}
 // Exhaust the real pool, including one bounded retry for every fourth error.
 const rounds=await page.evaluate(()=>{
  state=fresh();const normals=[],retries=[],expectedRetry=[],roundGroups=new Map();let lastRound=0,expectedGroups=[],drawn=[];
  for(let i=0;i<POOL.length*2+10;i++){
   const task=chooseTask();if(!task)break;const q=state.selection,r=q.reservations.at(-1);
   if(r.round!==lastRound){if(lastRound&&drawn.length!==expectedGroups.length)throw Error('incomplete number round');lastRound=r.round;drawn=[];const previous=new Set(q.used.slice(0,-1));expectedGroups=[...new Set(POOL.filter(t=>!previous.has(taskKey(t))).map(numberKey))];}
   if(r.kind==='normal'){normals.push(r.key);drawn.push(numberKey(task));const key=r.round+':'+numberKey(task);if(roundGroups.has(key))throw Error('number duplicate');roundGroups.set(key,true);}else{retries.push(r.key);if(r.key!==expectedRetry.shift())throw Error('retry motif or order changed');}
   state.active={task,selectionId:r.id,hadError:r.kind==='retry'||normals.length%4===0};
   if(r.kind==='normal'&&state.active.hadError)expectedRetry.push(r.key);
   completeSelection(state.active);completeSelection(state.active);
   // Selection survives exact JSON transport independently of the visual controls.
   state.selection=JSON.parse(JSON.stringify(state.selection));
  }
  return {normal:normals.length,unique:new Set(normals).size,retries:retries.length,remaining:expectedRetry.length,phase:state.selection.phase,rounds:lastRound,total:POOL.length};
 });assert.equal(rounds.normal,rounds.total);assert.equal(rounds.unique,rounds.total);assert.equal(rounds.retries,Math.floor(rounds.total/4));assert.equal(rounds.remaining,0);assert.equal(rounds.phase,'done');
 // Drawing reserves immediately, including a mode switch before any answer.
 await seed();await page.evaluate(()=>{state=fresh();newTask()});const first=await page.evaluate(()=>({key:taskKey(state.active.task),number:numberKey(state.active.task)}));await page.reload();assert.equal(await page.evaluate(()=>taskKey(state.active.task)),first.key);await page.locator('#mode').selectOption('multiply');assert.notEqual(await page.evaluate(()=>numberKey(state.active.task)),first.number);assert.equal(await page.evaluate(key=>state.selection.used.includes(key),first.key),true);
 const migration=await page.evaluate(()=>{state=fresh();const t=POOL[0],u=POOL.find(t=>taskKey(t)!==taskKey(POOL[0]));state.history=[{task:t,correct:false},{task:t,correct:false},{task:u,correct:false}];const q=ensureSelection();return {used:q.used.length,queue:q.queue.length,seen:q.seen.includes(numberKey(t))}});assert.deepEqual(migration,{used:2,queue:1,seen:true});
 const points=await page.evaluate(()=>{const task=POOL[0];return Array.from({length:20},(_,i)=>{state=fresh();const n=(i+1)*(i+4),quota=i<2?0:Math.ceil(n/5);state.history=Array.from({length:n},(_,k)=>({task,route:k<quota?'multiply':'divide',correct:true,attempts:[],work:[]}));save();return state.points})});assert.deepEqual(points,Array.from({length:20},(_,i)=>i+1));
 await page.goto(base+'/host');let frame=page.frames().find(f=>f.url().includes('/app'));await frame.locator('#exercise').waitFor();await solve(frame);initial=await page.locator('textarea').inputValue();assert.ok(initial.startsWith('EINHEIT:'));assert.equal(JSON.parse(Buffer.from(initial.slice(8),'base64')).history[0].attempts.length,6);assert.equal(await page.locator('#e1').isVisible(),false);await frame.evaluate(()=>{state.points=20;save()});assert.deepEqual(await page.locator('#e2 input').evaluateAll(es=>es.map(e=>e.value)),Array(20).fill('1'));await page.reload();frame=page.frames().find(f=>f.url().includes('/app'));await frame.locator('#exercise').waitFor();assert.equal(await frame.evaluate(()=>state.history.length),1);
 initial='foreign';await page.goto(base+'/host');frame=page.frames().find(f=>f.url().includes('/app'));await frame.locator('#retry').waitFor();assert.equal(await page.locator('textarea').inputValue(),'foreign');
 await page.goto(base+'/inline');await page.addScriptTag({path:path.resolve(__dirname,'../../../Chemie/Edulo Laborführerschen/Widget_224324_Luft_und_Gas_Regulieren.wdgt/libs/jquery-2.1.1.min.js')});const script=raw.match(/<script>([\s\S]*?)<\/script>/)[1];assert.equal(await page.evaluate(raw=>window.$(raw).find('script').addBack('script').last().text(),raw),script);
 const body=html.match(/<body[^>]*>([\s\S]*)<\/body>/)[1],style=raw.match(/<style>([\s\S]*)<\/style>/)[1];for(let i=0;i<3;i++){await page.evaluate(({body,style})=>window.$('#slot').empty().append(window.$('<style>'+style+'</style>'+body)),{body,style});await page.locator('#exercise').waitFor();await seed('divide',i===0?'chocolate':i===1?'minutes':'tape');await solve();assert.equal(await page.locator('svg rect rect,svg path path').count(),0);if(i===0)assert.equal(await page.locator('[data-chocolate-piece]').count(),24);assert.equal(await page.locator('#e1').isVisible(),true);await page.locator('#help').click();await page.locator('#closeIntro').click();}assert.equal(await page.locator('textarea').inputValue(),'');
 await page.goto(require('node:url').pathToFileURL(file).href);await page.locator('#exercise').waitFor();assert.match(await page.locator('#storage').textContent(),/diesem Browser gespeichert/);assert.deepEqual(errors,[]);console.log('PASS',report,'all routes, conversion errors, reloads, 20 thresholds, mobile, real jQuery, host and browser fallback');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();server.close()});
