const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),os=require('node:os');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const file=path.join(__dirname,'../Anteile berechnen - Layout 2.html'),raw=fs.readFileSync(file,'utf8');
const hooks=`Object.defineProperty(window,'state',{configurable:true,get:()=>state,set:v=>state=v});Object.assign(window,{fresh,render,save,POOL,SCENES,expected,rationalText,partitionOptions,parseState,encodeState});`;
const html=raw.replace(/connect\(\);\s*\}\)\(\);/,hooks+'connect();})();');
const fields='<div id="e1"><textarea id="e1_text_input"></textarea></div><div id="e2">'+Array.from({length:20},(_,i)=>`<input id="e2_cloze_text_input_${i+1}">`).join('')+'</div>';
let browser;const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html;charset=utf-8');res.end(req.url.startsWith('/inline')?'<body class="editor">'+fields+'<div id="slot"></div></body>':req.url.startsWith('/host')?html.replace('<body>','<body>'+fields+'<script>window.widget={};</script>'):html);});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:920,height:728},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:'+server.address().port;await page.goto(base+'/host');await page.locator('#exercise').waitFor();
 async function seed(mode='divide',scene='rope',stage=null){await page.evaluate(({mode,scene,stage})=>{state=fresh();state.mode=mode;const task=POOL.find(t=>t.scene===scene&&t.whole===6&&t.n===2&&t.d===3)||POOL.find(t=>t.scene===scene&&t.n===3&&t.d===4)||POOL.find(t=>t.scene===scene);state.active={task,mode,route:mode==='choice'?null:mode,stage:stage||(mode==='choice'?'route':mode==='divide'?'divideParts':'copies'),parts:1,copies:1,selected:[],input:'',attempts:[],hadError:false,work:[],started:new Date().toISOString()};render();save();},{mode,scene,stage});}
 async function advance(route='divide'){const a=await page.evaluate(()=>state.active);if(a.stage==='route')await page.locator(`[data-route=${route}]`).click();else if(['divideParts','copies','multiplyParts'].includes(a.stage)){await page.locator('#range').fill(String(await page.evaluate(()=>state.active.stage==='copies'?state.active.task.n:partitionOptions(state.active.task).indexOf(state.active.task.d)+1)));await page.locator('#checkRange').click();}else if(a.stage==='mark'){for(let i=0;i<a.task.n;i++)if(!a.selected.includes(i))await page.locator(`[data-part="${i}"]`).press('Enter');await page.locator('#checkMark').click();}else{await page.locator('#answer').fill(await page.evaluate(()=>rationalText(expected(state.active))));await page.locator('#checkAnswer').click();}}
 const screenshotDir=path.join(os.tmpdir(),'anteile-layout2');fs.mkdirSync(screenshotDir,{recursive:true});
 for(const [mode,route] of [['divide','divide'],['multiply','multiply'],['choice','divide'],['choice','multiply']]){
  await seed(mode);const visited=[];for(let step=0;step<7;step++){if(await page.evaluate(()=>state.active.stage==='done'))break;visited.push(await page.evaluate(()=>state.active.stage));
   assert.equal(await page.locator('#work').isVisible(),false);assert.equal(await page.locator('#flow').isVisible(),false);
   const visible=await page.evaluate(()=>{const pic=document.querySelector('.object > svg').getBoundingClientRect(),bar=document.querySelector('.board-controls').getBoundingClientRect();return {picTop:pic.top,picBottom:pic.bottom,barBottom:bar.bottom,overflow:document.documentElement.scrollWidth>innerWidth}});assert.ok(visible.picTop>=0&&visible.picBottom<728&&visible.barBottom<728,JSON.stringify(visible));assert.equal(visible.overflow,false);
   if(mode==='divide')await page.screenshot({path:path.join(screenshotDir,'divide-'+step+'.png')});await advance(route);
  }assert.deepEqual(visited,[...(mode==='choice'?['route']:[]),...(route==='divide'?['divideParts','unit','mark','result']:['copies','product','multiplyParts','result'])]);assert.equal(await page.evaluate(()=>state.active.stage),'done');assert.equal(await page.evaluate(()=>state.history[0].correct),true);assert.equal(await page.locator('[data-equation]').count(),2);
 }
 assert.equal(await page.locator('#standaloneHeading').isVisible(),false);
 await seed();await page.locator('#checkRange').click();assert.equal(await page.locator('#stepTip').isVisible(),true);await advance();await page.locator('#answer').fill('12/6');await page.locator('#checkAnswer').click();assert.equal(await page.evaluate(()=>state.active.stage),'unit');assert.equal(await page.evaluate(()=>state.active.hadError),true);await page.locator('#answer').fill('2');await page.locator('#answer').press('Enter');assert.equal(await page.evaluate(()=>state.active.stage),'mark');
 const saved=await page.locator('#e1_text_input').inputValue();assert.ok(saved.startsWith('ANTEIL2:'));await page.evaluate(text=>{state=parseState(text);render();},saved);assert.equal(await page.evaluate(()=>state.active.stage),'mark');
 // Every scene remains usable in the compact area, both portrait and landscape.
 for(const width of [920,390]){await page.setViewportSize({width,height:728});for(const scene of await page.evaluate(()=>SCENES.map(s=>s.id))){await seed('divide',scene,'mark');assert.equal(await page.locator('.object > svg').count(),1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,scene+' overflow');}await page.screenshot({path:path.join(screenshotDir,'width-'+width+'.png'),fullPage:true});}
 await page.setViewportSize({width:920,height:506});await seed();const compact=await page.locator('.board-controls').boundingBox();assert.ok(compact.y+compact.height<506,JSON.stringify(compact));await page.screenshot({path:path.join(screenshotDir,'short-viewport.png')});
 // Slider geometry is independent of label length; quantities stay on one line.
 await page.setViewportSize({width:920,height:728});
 for(const mode of ['divide','multiply']){await seed(mode);const before=await page.locator('#range').boundingBox();await page.locator('#range').fill(await page.locator('#range').getAttribute('max'));const after=await page.locator('#range').boundingBox();assert.equal(before.x,after.x);assert.equal(before.width,after.width);}
 for(const scene of ['butter','tape','minutes']){
  await seed('divide',scene,'mark');await page.evaluate(()=>{state.active.work=['Ein Teil berechnet'];state.active.selected=[0];render();});
  const labels=page.locator('[data-part-amount]');assert.ok(await labels.count()>0);
  assert.ok(await labels.evaluateAll(es=>es.every(e=>e.querySelectorAll('text').length===1)));
  if(scene==='butter'){assert.equal(await page.locator('[data-region="0"] [data-block-top]').getAttribute('fill'),'#65c7a8');assert.ok(await page.locator('.object svg').textContent().then(t=>/g Butter/.test(t)));}
  await page.screenshot({path:path.join(screenshotDir,'refined-'+scene+'.png')});
 }
 // Touch remains functional after cropping/repositioning the SVG drawing.
 await page.setViewportSize({width:920,height:728});await seed('divide','rope','mark');
 const pts=await page.locator('[data-part]').evaluateAll(es=>es.slice(0,2).map(el=>{const r=el.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};}));const cdp=await page.context().newCDPSession(page);const touch=async(type,p)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:p?[{x:p.x,y:p.y,id:1}]:[]});await touch('touchStart',pts[0]);await touch('touchMove',pts[1]);await touch('touchEnd');assert.deepEqual(await page.evaluate(()=>state.active.selected),[0,1]);await page.locator('#checkMark').click();await page.locator('#answer').fill('4');await page.locator('#checkAnswer').click();assert.equal(await page.evaluate(()=>state.history[0].correct),true);
 // Real jQuery insertion must preserve script and form event handlers.
 await page.goto(base+'/inline');await page.addScriptTag({path:path.resolve(__dirname,'../../../Chemie/Edulo Laborführerschen/Widget_224324_Luft_und_Gas_Regulieren.wdgt/libs/jquery-2.1.1.min.js')});assert.equal(await page.evaluate(raw=>window.$(raw).find('script').addBack('script').last().text(),raw),raw.match(/<script>([\s\S]*?)<\/script>/)[1]);const body=html.match(/<body[^>]*>([\s\S]*)<\/body>/)[1],style=raw.match(/<style>([\s\S]*?)<\/style>/)[1];for(let i=0;i<2;i++){await page.evaluate(({body,style})=>window.$('#slot').empty().append(window.$('<style>'+style+'</style>'+body)),{body,style});await page.locator('#exercise').waitFor();await seed();for(let k=0;k<4;k++)await advance();assert.equal(await page.evaluate(()=>state.active.stage),'done');}
 await page.goto(require('node:url').pathToFileURL(file).href);await page.locator('#exercise').waitFor();assert.equal(await page.locator('#standaloneHeading').isVisible(),true);await page.locator('#help').click();await page.locator('#closeIntro').click();assert.deepEqual(errors,[]);console.log('PASS compact layout: four routes, 20 scenes, viewport fit, numeric input, independent storage, legacy jQuery and standalone title. Screenshots:',screenshotDir);
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();server.close()});
