const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),os=require('node:os');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const names=['Anteile berechnen.html','Das Ganze bestimmen.html','Anteile berechnen 2.html'];
const sources=names.map(n=>fs.readFileSync(path.join(__dirname,'..',n),'utf8').replace(/\r\n/g,'\n'));
const hooks=`Object.defineProperty(window,'state',{configurable:true,get:()=>state,set:v=>state=v});Object.assign(window,{fresh,render,save,newTask,POOL,SCENES,expected,rationalText,partitionOptions,parseState,encodeState});`;
const fields='<div id="e1"><textarea id="e1_text_input"></textarea></div><div id="e2">'+Array.from({length:20},(_,i)=>`<input id="e2_cloze_text_input_${i+1}">`).join('')+'</div>';
let initial='',browser;const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html;charset=utf-8');const i=Number(req.url.slice(1))||0;res.end(sources[i].replace(/connect\(\);\s*\}\)\(\);/,hooks+'connect();})();').replace('<body>','<body>'+fields.replace('</textarea>',initial+'</textarea>')+'<script>window.widget={};</script>'));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:920,height:728},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:'+server.address().port,shots=path.join(os.tmpdir(),'fractions-layout-final');fs.mkdirSync(shots,{recursive:true});
for(let app=0;app<3;app++){
 const legacy=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures',names[app]+'.legacy.json'),'utf8'));initial=legacy.encoded;await page.goto(base+'/'+app);await page.locator('#exercise').waitFor();assert.deepEqual(await page.evaluate(()=>state),legacy.state,'Legacy E1 state preserved');assert.equal(await page.locator('#e1_text_input').inputValue(),legacy.encoded);initial='';
 async function seed(mode,scene){await page.evaluate(({mode,scene})=>{state=fresh();state.mode=mode;newTask();if(scene){state.active.task=POOL.find(t=>t.scene===scene&&t.n===3&&t.d===4)||POOL.find(t=>t.scene===scene);render();save();}},{mode,scene});}
 async function advance(route){const a=await page.evaluate(()=>state.active);if(a.stage==='route')await page.locator(`[data-route=${route}]`).click();else if(a.stage==='selectUnit'){await page.locator('#unitSelect').selectOption(await page.evaluate(()=>SCENES.find(s=>s.id===state.active.task.scene).unit));await page.locator('#checkUnit').click();}else if(['divideParts','copies','multiplyParts'].includes(a.stage)){await page.locator('#range').fill(String(await page.evaluate(whole=>state.active.stage==='copies'?(whole?state.active.task.d:state.active.task.n):partitionOptions(state.active.task).indexOf(state.active.stage==='multiplyParts'&&whole?state.active.task.n:state.active.task.d)+1,app===1)));await page.locator('#checkRange').click();}else if(a.stage==='mark'){for(let i=0;i<a.task.n;i++)if(!a.selected.includes(i))await page.locator(`[data-part="${i}"]`).press('Enter');await page.locator('#checkMark').click();}else{await page.locator('#answer').fill(await page.evaluate(()=>rationalText(expected(state.active))));await page.locator('#checkAnswer').click();}}
 for(const [mode,route] of [['divide','divide'],['multiply','multiply'],['choice','divide'],['choice','multiply']]){
  await seed(mode);const visited=[];
  for(let k=0;k<10;k++){const stage=await page.evaluate(()=>state.active.stage);if(stage==='done')break;visited.push(stage);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,names[app]+stage);await advance(route);const before=await page.evaluate(()=>JSON.stringify(state));initial=await page.locator('#e1_text_input').inputValue();await page.reload();await page.locator('#exercise').waitFor();assert.equal(await page.evaluate(()=>JSON.stringify(state)),before,'E1 reload '+names[app]+stage);}
  const expected=[...(app===2?['selectUnit','convert']:[]),...(mode==='choice'?['route']:[]),...(app===1?(route==='divide'?['divideParts','mark','unit','result']:['divideParts','mark','copies','product','result']):(route==='divide'?['divideParts','unit','mark','result']:['copies','product','multiplyParts','result']))];assert.deepEqual(visited,expected);assert.equal(await page.evaluate(()=>state.history.at(-1).correct),true);
 }
 for(const width of [920,390]){await page.setViewportSize({width,height:728});for(const scene of await page.evaluate(()=>SCENES.map(s=>s.id))){await seed('divide',scene);for(let k=0;k<8;k++){const stage=await page.evaluate(()=>state.active.stage);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,names[app]+scene+stage);if(width===920&&['butter','minutes','tape'].includes(scene))await page.screenshot({path:path.join(shots,app+'-'+scene+'-'+stage+'.png')});if(stage==='done')break;await advance('divide');}}}
 await page.setViewportSize({width:920,height:728});console.log('PASS',names[app],'both routes including choice, reload every step, all scenes at two widths');
}
assert.deepEqual(errors,[]);console.log('Screenshots:',shots);
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();server.close()});
