(function(global){
 'use strict';
 const NS='dynamot-learning-v2',copy=x=>JSON.parse(JSON.stringify(x));
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function graph(value){
  const nodes=[],edges=[],a=value.main;
  if(a.some((t,i)=>!t||t.kind!==(i%2?'device':'energy')))return {nodes:[],edges:[]};
  a.forEach((t,i)=>{if(i%2)nodes.push({id:'station'+i,label:t.label});else edges.push({from:i?'station'+(i-1):null,to:i<a.length-1?'station'+(i+1):null,energy:t.label});});
  value.branches.forEach(b=>edges.push({from:'station'+b.from,to:null,energy:b.energy}));return {nodes,edges};
 }
 function mount(root){
  const lab=root.energyLab,Tasks=global.DynamotTasks,Diagram=global.DynamotDiagram;if(!lab||!Tasks||!Diagram)return;
  const host=document.createElement('section');host.className='learn';host.setAttribute('aria-label','Vier Versuche zur Energie');root.querySelector('.storage').before(host);
  let engine=null,store={version:2,drafts:{},builds:{},notes:{}},chosen=null,busy=false,blocked=false,diagram=null,referenceView=null,feedback='',feedbackBad=false,lastEvidenceSave=0;
  const numberOf=id=>Tasks.experiments.findIndex(e=>e.id===id)+1;
  function status(){return lab.getPersistenceStatus?.()||{ready:true,blocked:false,editor:false,edulo:parent!==window};}
  function score(){
   const st=status();if(st.blocked||st.editor||!st.edulo||blocked)return;
   const docs=lab.hostDocuments();
   const prefix=new URLSearchParams(location.search).get('SCORE_PREFIX')||'e2_cloze_text_input_';
   const fields=Array.from({length:20},(_,i)=>docs.map(d=>d.getElementById(prefix+(i+1))).find(Boolean));
   if(fields.some(f=>f&&String(f.value).trim()&&!['0','1'].includes(String(f.value)))){host.querySelector('.learn-storage').textContent='Punktefelder enthalten fremde Werte und bleiben unverändert.';return;}
   for(let i=0;i<fields.length;i++){const f=fields[i];if(!f)continue;const value=i<engine.progress().points?'1':'0';if(f.value!==value){const setter=Object.getOwnPropertyDescriptor(Object.getPrototypeOf(f),'value')?.set;if(setter)setter.call(f,value);else f.value=value;for(const t of ['input','change'])f.dispatchEvent(new f.ownerDocument.defaultView.Event(t,{bubbles:true}));}lab.hideHostField(f,'e2');}
   host.querySelector('.learn-storage').textContent=fields.every(Boolean)?'20 Punktefelder an Edulo übergeben.':'Edulo: '+fields.filter(Boolean).length+' von 20 Punktefeldern verbunden.';
  }
  function capturePage(){if(!engine||!chosen)return;store.pages??={};store.pages[chosen]={scroll:host.scrollTop,open:[...host.querySelectorAll('details[open]')].map(d=>d.querySelector('summary')?.textContent)};}
  let scrollSave;
  host.addEventListener('scroll',()=>{capturePage();clearTimeout(scrollSave);scrollSave=setTimeout(save,150);});
  host.addEventListener('toggle',()=>{capturePage();save();},true);
  function save(){if(busy||blocked||!engine||status().blocked)return;busy=true;try{store.engine=engine.serialize();store.chosen=chosen;if(lab.setTaskState(NS,store)===true)score();}catch(e){host.querySelector('.learn-storage').textContent='Aufgabenstand nicht gespeichert: '+e.message;}finally{busy=false;}}
  function savedChoice(){return store.chosen==='summary'||store.chosen==='free'||Tasks.experiments.some(e=>e.id===store.chosen)?store.chosen:engine.current()?.experiment||'free';}
  function boot(){if(engine||!status().ready)return;try{const saved=lab.getTaskState(NS);if(saved!==null){if(saved.version!==2||!saved.engine||![saved.drafts,saved.builds,saved.notes].every(v=>v&&typeof v==='object'&&!Array.isArray(v))||Object.values(saved.notes).some(v=>typeof v!=='string'||v.length>3000))throw Error('Unbekanntes Aufgabenformat');for(const [id,v]of Object.entries(saved.drafts)){const d=Tasks.definitions.find(d=>d.id===id);if(!d||!v||typeof v!=='object')throw Error('Beschädigter Entwurf');if(d.kind==='diagram'&&(!Array.isArray(v.main)||v.main.length!==d.chain.length||v.main.some(t=>t&&(!['energy','device'].includes(t.kind)||typeof t.label!=='string'))||!Array.isArray(v.branches)||v.branches.some(b=>!Number.isInteger(b.from)||b.from<0||b.from>=v.main.length||b.energy!=='thermische Energie')))throw Error('Beschädigtes Diagramm');}for(const v of Object.values(saved.builds))if(!v||!Array.isArray(v.devices)||!Array.isArray(v.wires))throw Error('Beschädigter Aufbau');store=saved;}engine=Tasks.create({state:store.engine});}catch(e){blocked=true;lab.blockPersistence?.('Der gespeicherte Aufgabenstand ist nicht lesbar');store={version:2,drafts:{},builds:{},notes:{}};engine=Tasks.create();feedback='Der gespeicherte Aufgabenstand ist nicht lesbar. Er bleibt unverändert. Die Aufgaben können hier ohne Speicherung ausprobiert werden.';}chosen=savedChoice();if(chosen!=='summary')lab.setMode(chosen);render();queueMicrotask(save);}
  function activity(){const a=engine.activity(chosen),current=engine.current(chosen);if(current?.kind!=='observe')return '';const labels={comparison:'Langsam/schnell verglichen',normal:'Normale Polung beobachtet',swapped:'Vertauschte Polung beobachtet',reverse:'Drehrichtung umgekehrt',speed:'Langsam/schnell verglichen',lift:'Gewicht angehoben',fall:'Fall beobachtet'};if(current.experiment==='v4')labels.comparison='Leichteres/schwereres Gewicht verglichen';const keys={v1:['comparison'],v2:['normal','reverse','swapped','speed'],v3:['lift'],v4:['fall','comparison']}[current.experiment];return '<ul class="learn-checklist">'+keys.map(k=>`<li class="${a[k]?'learn-done':''}">${a[k]?'✓':'○'} ${labels[k]}</li>`).join('')+'</ul>';}
  function reference(){return '<section class="learn-reference"><h3>Vorlage · so soll dein Aufbau aussehen</h3><div class="learn-reference-stage" aria-label="Drehbare 3D-Vorlage des Aufbaus"></div></section>';}
  function displayText(step){if(step.kind==='build')return {v1:'Baue einen DynaMot mit Kurbel, eine Lampe und zwei Kabel wie in der 3D-Vorlage auf. Verbinde auf derselben Tischseite DynaMot rot mit Lampe schwarz und DynaMot schwarz mit Lampe rot.',v4:'Baue einen DynaMot mit Seilrolle und Gewicht, eine Lampe und zwei Kabel wie in der 3D-Vorlage auf. Verbinde auf derselben Tischseite DynaMot rot mit Lampe schwarz und DynaMot schwarz mit Lampe rot.',v2:'Baue zwei DynaMots mit je einer Kurbel und zwei Kabel wie in der 3D-Vorlage auf.',v3:'Baue zwei DynaMots mit Kurbel sowie Seilrolle und Gewicht wie in der 3D-Vorlage auf.'}[step.experiment];if(step.kind==='observe'&&step.experiment==='v2')return step.text.replace('Vertausche danach am zweiten DynaMot die beiden Kabel','Nutze danach „Polung umkehren“');return step.text;}
  function displayHints(step){return step.hints?.map(h=>{if(['v1','v4'].includes(step.experiment)&&h.startsWith('Verbinde beide DynaMot-Buchsen'))return 'Verbinde auf derselben Tischseite DynaMot rot mit Lampe schwarz und DynaMot schwarz mit Lampe rot.';return h.replace('Nimm am zweiten DynaMot die Kurbel ab und bringe die Seilrolle an.','Bringe am zweiten DynaMot die Seilrolle mit Gewicht an.').replace('Ersetze die Kurbel durch die Seilrolle.','Bringe am DynaMot die Seilrolle mit Gewicht an.').replace('„Kurbeln“','„Antreiben“');})||[];}
  function records(ex){const record=store.builds[ex.id];return record?`<div class="learn-build-record">${record.devices.map(d=>`<span>${d.type==='lamp'?'Lampe':'DynaMot'} ${d.id} · ${esc(d.slot)}${d.crank?' · Kurbel':d.weight?' · Gewicht':''}</span>`).join('')}</div><p class="sub">${record.wires.map(w=>`Kabel: ${w.a}/${w.ap===0?'rot':'schwarz'} ↔ ${w.b}/${w.bp===0?'rot':'schwarz'}`).join(' · ')}</p>`:'<p class="sub">Noch kein geprüfter Aufbau gespeichert.</p>';}
  function review(ex){return `<details class="learn-summary" ${chosen===ex.id?'open':''}><summary>Versuch ${numberOf(ex.id)} · ${esc(ex.title)}</summary>${records(ex)}<p>${esc(ex.summary)}</p><ul class="learn-checklist">${ex.steps.map(s=>`<li class="${s.completed?'learn-done':''}">${s.completed?'✓':'○'} ${esc(s.text)}${s.kind==='choice'&&s.response?'<ul>'+s.questions.map(q=>`<li>${esc(q.text)} <strong>${esc(s.response[q.id])}</strong></li>`).join('')+'</ul>':''}</li>`).join('')}</ul>${ex.steps.find(s=>s.kind==='diagram'&&s.completed)?`<div data-review-diagram="${ex.id}"></div>`:''}${store.notes[ex.id]?`<p><strong>Eigene Notizen:</strong> ${esc(store.notes[ex.id])}</p>`:''}</details>`;}
  function render(){
   diagram?.destroy();diagram=null;referenceView?.dispose();referenceView=null;const p=engine.progress(),cur=engine.current(chosen),result=engine.results();
    host.innerHTML=`<div class="learn-top"><div><h2>Dein Auftrag</h2><p class="sub">Aufbauen → beobachten → ergänzen → Energiefluss zeigen</p></div><span class="learn-score">${p.points} von 20 Punkten</span></div><progress value="${p.points}" max="20" aria-label="Lernfortschritt"></progress><nav class="learn-nav" aria-label="Versuche">${result.experiments.map(e=>`<button type="button" data-learn-nav="${e.id}" aria-current="${chosen===e.id}">${e.steps.every(s=>s.completed)?'✓ ':''}${numberOf(e.id)} · ${esc(e.title)}</button>`).join('')}<button type="button" data-learn-nav="free" aria-current="${chosen==='free'}">Freies Labor</button><button type="button" data-learn-nav="summary" aria-current="${chosen==='summary'}">Nachschlagewerk</button></nav><div class="learn-body"></div><p class="learn-feedback ${feedbackBad?'bad':''}" role="status">${esc(feedback)}</p><p class="learn-storage sub"></p><details><summary>So sammelst du Punkte</summary><p>Jeder Versuch gibt 5 Punkte: Aufbau 1, Durchführung 1, richtige Beobachtungen 1 und Energieflussdiagramm 2. Du darfst Antworten und Diagramme verbessern. Hilfe kostet keine Punkte.</p><p>Die Simulation prüft deinen virtuellen Aufbau und seine Bewegung. Beim echten Experiment könnt ihr zu zweit, zu dritt oder zu viert arbeiten und eure Beobachtungen zusätzlich notieren.</p></details>`;
   root.dataset.learningStep=chosen==='summary'?'summary':cur?.kind||'review';
   const picker=document.createElement('select');picker.className='learn-picker';picker.setAttribute('aria-label','Versuch oder Nachschlagewerk wählen');
    picker.innerHTML=result.experiments.map((e,i)=>`<option value="${e.id}" ${chosen===e.id?'selected':''}>${i+1} · ${esc(e.title)}</option>`).join('')+`<option value="free" ${chosen==='free'?'selected':''}>Freies Labor</option><option value="summary" ${chosen==='summary'?'selected':''}>Nachschlagewerk</option>`;
   host.querySelector('.learn-nav').after(picker);
   const body=host.querySelector('.learn-body');
   if(chosen==='free'){body.innerHTML='<h3>Freies Labor</h3><p>Hier kannst du Geräte, Zubehör und Kabel frei ausprobieren. Die vier geführten Versuche behalten jeweils ihren eigenen Aufbau.</p>';}else if(chosen==='summary'){body.innerHTML=`<h3>${p.done?'Alle vier Versuche geschafft!':'Dein Nachschlagewerk'}</h3><p>Hier bleiben geprüfte Aufbauten, Beobachtungen und Diagramme erhalten.</p>${result.experiments.map(review).join('')}`;}
   else if(!cur){const ex=result.experiments.find(e=>e.id===chosen);body.innerHTML=review(ex);}
   else{
    const ex=result.experiments.find(e=>e.id===chosen);const draft=store.drafts[cur.id]||{};
    body.innerHTML=`<h3>Versuch ${numberOf(chosen)} · ${esc(ex.title)}</h3><ul class="learn-checklist learn-stepstrip">${ex.steps.filter(s=>s.completed).map(s=>`<li class="learn-done">✓ ${esc({build:'Aufbau stimmt',observe:'Versuch durchgeführt',choice:'Beobachtungen ergänzt',diagram:'Diagramm stimmt'}[s.kind])}</li>`).join('')}</ul><div class="learn-current">${cur.kind==='diagram'?'':`<p><strong>${esc(displayText(cur))}</strong></p>`}${cur.kind==='build'?`<p class="sub">Der richtige Aufbau wird automatisch erkannt.</p><details><summary>Hilfe zum Aufbau</summary><ol>${displayHints(cur).map(h=>'<li>'+esc(h)+'</li>').join('')}</ol></details>`:cur.kind==='observe'?`<p class="sub">${cur.experiment==='v4'?'Wähle den DynaMot, setze das Gewicht hoch und starte die Simulation. Zum Wechseln der Masse pausieren, Masse ändern und erneut hochsetzen.':'Wähle den antreibenden DynaMot, schalte „Antreiben“ ein und starte die Simulation. Tempo und Drehrichtung kannst du nach dem Pausieren ändern. Bei Versuch 3 kehrst du die Polung mit der Taste um.'}</p><div class="learn-activity">${activity()}</div>`:cur.kind==='choice'?`<form class="learn-answer">${cur.questions.map(q=>`<label>${esc(q.text)} <select name="${esc(q.id)}" required aria-label="${esc(q.text)}"><option value="">Bitte wählen …</option>${q.options.map(o=>`<option ${draft[q.id]===o?'selected':''}>${esc(o)}</option>`).join('')}</select><span data-answer-feedback="${q.id}"></span></label>`).join('')}<button type="submit" class="primary">Antworten prüfen</button></form>`:`<div class="learn-diagram"></div><button type="button" class="primary" data-check-diagram>Diagramm prüfen</button><details><summary>Hinweis zur Energie</summary><p class="sub">${esc(cur.note)}</p></details>`}</div><details><summary>Eigene Beobachtungen / echtes Experiment</summary><label>Notizen zu Versuch ${numberOf(chosen)}<textarea class="learn-notes" rows="3" maxlength="3000" style="width:100%;font:inherit">${esc(store.notes[chosen]||'')}</textarea></label></details>`;
    if(cur.kind==='diagram')diagram=Diagram.mount(body.querySelector('.learn-diagram'),{length:cur.chain.length,devices:[...new Set(cur.chain.filter((_,i)=>i%2))],value:store.drafts[cur.id],onChange(v){store.drafts[cur.id]=v;save();}});
   }
    if(chosen!=='free'&&chosen!=='summary'){const snapshot=lab.getSnapshot();if(!snapshot.buildLocked){body.insertAdjacentHTML('afterbegin',reference());referenceView=lab.mountReference?.(body.querySelector('.learn-reference-stage'),chosen)||null;}if(snapshot.modeSource==='reconstructed')body.insertAdjacentHTML('afterbegin','<p class="sub">Aus dem früher geprüften Aufbau wiederhergestellt.</p>');}
    const pageState=store.pages?.[chosen];if(pageState){for(const d of host.querySelectorAll('details'))d.open=pageState.open?.includes(d.querySelector('summary')?.textContent)||false;host.scrollTop=Number.isFinite(pageState.scroll)?pageState.scroll:0;}
   host.querySelectorAll('[data-review-diagram]').forEach(el=>{const ex=result.experiments.find(e=>e.id===el.dataset.reviewDiagram);Diagram.mount(el,{length:ex.chain.length,value:store.drafts[ex.id+'.diagram'],readonly:true});});
   if(blocked)host.querySelector('.learn-storage').textContent='Speicherschutz aktiv: Bestehender Aufgabenstand bleibt erhalten.';
  }
  function completed(){feedback=engine.progress().done?'✓ Alle vier Versuche abgeschlossen. Dein Nachschlagewerk ist fertig.':engine.current(chosen)?'✓ Richtig – der nächste Schritt in diesem Versuch ist bereit.':'✓ Versuch abgeschlossen. Du kannst einen anderen Versuch wählen.';feedbackBad=false;render();save();}
  function event(e){if(busy)return;boot();if(!engine||chosen==='summary'||chosen==='free')return;const snapshot=e.detail?.snapshot||lab.getSnapshot();if(snapshot.activeMode!==chosen)return;const before=engine.current(chosen);if(!snapshot.buildLocked&&before?.kind!=='build'&&lab.lockBuild(chosen))render();if(!before||!['build','observe'].includes(before.kind))return;const changed=engine.observe(Tasks.fromLab(snapshot),chosen);if(changed){if(before.kind==='build'){store.builds[before.experiment]=copy({devices:snapshot.devices,wires:snapshot.wires});lab.lockBuild(before.experiment);}completed();}else{const el=host.querySelector('.learn-activity');if(el)el.innerHTML=activity();if(before.kind==='observe'&&performance.now()-lastEvidenceSave>1500){lastEvidenceSave=performance.now();save();}}}
   host.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!engine)return;if(b.dataset.learnNav){capturePage();chosen=b.dataset.learnNav;if(chosen!=='summary')lab.setMode(chosen);feedback='';render();save();}else if(b.hasAttribute('data-check-diagram')){const response=engine.submitDiagram(graph(diagram.getValue()),chosen);if(response.correct)completed();else{feedback='Das passt noch nicht. Prüfe die Reihenfolge: Energiepfeil → Gerätekasten → Energiepfeil. Beginne bei der zugeführten Energie und ende beim Ergebnis.';feedbackBad=true;const f=host.querySelector('.learn-feedback');f.textContent=feedback;f.classList.add('bad');save();}}});
  host.addEventListener('submit',e=>{if(!e.target.matches('.learn-answer'))return;e.preventDefault();const values=Object.fromEntries(new FormData(e.target));const id=engine.current(chosen).id;store.drafts[id]=values;const result=engine.answer(values,chosen);if(result.correct)completed();else{for(const [k,ok]of Object.entries(result.feedback||{})){const el=host.querySelector(`[data-answer-feedback="${k}"]`);el.textContent=ok?' ✓':' · Bitte noch einmal überlegen.';}feedback='Noch nicht alles richtig. Du kannst deine Auswahl ändern.';host.querySelector('.learn-feedback').textContent=feedback;save();}});
   host.addEventListener('change',e=>{if(e.target.matches('.learn-picker')){capturePage();chosen=e.target.value;if(chosen!=='summary')lab.setMode(chosen);feedback='';render();save();return;}if(e.target.closest('.learn-answer')){store.drafts[engine.current(chosen).id]=Object.fromEntries(new FormData(e.target.closest('form')));save();}});
  host.addEventListener('input',e=>{if(e.target.matches('.learn-notes')){store.notes[chosen]=e.target.value;save();}});
  root.addEventListener('dynamot:state',event);const timer=setInterval(()=>{if(!root.isConnected){clearInterval(timer);return;}boot();if(engine)clearInterval(timer);},200);
  boot();
 }
 global.DynamotLearning={mount,graph};
})(globalThis);
