// One shared diagram: build the main route, then reveal six energy branches.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const dir=path.resolve(__dirname,'..');const api=require(path.join(dir,'learning.js'));
const chain=['chemische Energie','Muskel','kinetische Energie','Luftpumpe','thermische Energie','Flasche','kinetische Energie','Flasche','Lageenergie','Flasche','kinetische Energie'];
const oldChain=['chemische Energie','Muskeln','kinetische Energie','Luftpumpe','thermische Energie','Druckluft und Düse','kinetische Energie','Rakete und Erde (Steigen)','Lageenergie','Rakete und Erde (Fallen)','kinetische Energie'];
const branches=['thermische Energie','thermische Energie','thermische Energie','kinetische Energie','thermische Energie','thermische Energie'];

// A genuine V2 shape has both complete main routes and only two branches.
const old=api.rocketLearningFresh();old.version=2;old.drafts.basic.main=oldChain.slice();old.drafts.losses.main=oldChain.slice();old.drafts.losses.branches=['thermische Energie','kinetische Energie'];old.drafts.cloze=['chemische Energie','kinetische Energie','thermische Energie','kinetische Energie','Lageenergie','kinetische Energie'];old.solved.fill(true);old.attempts[8]=2;old.hints[19]=true;old.carryScores20[0]='green';old.carryScores20[8]='yellow';
const snapshot=JSON.stringify(old),migrated=api.rocketLearningMigrate(old);
assert(api.rocketLearningValidate(old));assert(api.rocketLearningValidate(migrated));assert.equal(migrated.version,3);assert.deepEqual(migrated.drafts.basic.main,chain);assert.deepEqual(migrated.drafts.losses.branches,['','thermische Energie','','kinetische Energie','','']);assert.deepEqual(migrated.legacyV2,old);assert.equal(JSON.stringify(old),snapshot,'migration must not mutate stored data');assert.deepEqual(api.rocketLearningMigrate(migrated),migrated,'migration is idempotent');
assert.equal(migrated.carryScores20.length,20);assert.equal(migrated.carryScores20[0],'green');assert.equal(migrated.carryScores20[8],'yellow');assert.equal(migrated.carryScores20[18],'green');assert.equal(migrated.carryScores20[19],'yellow');assert.equal(migrated.solved[13],true);assert.equal(migrated.solved[15],true);
const distractor=structuredClone(old);distractor.drafts.basic.main[1]='Solarzelle';distractor.drafts.losses.main[1]='Elektromotor';assert.equal(api.rocketLearningMigrate(distractor).drafts.basic.main[1],'Solarzelle');
const currentDistractor=api.rocketLearningFresh();currentDistractor.drafts.basic.main[1]='Elektromotor';assert(api.rocketLearningValidate(currentDistractor),'retired converter in saved V3 draft remains valid');

const diagramTop=page=>page.evaluate(()=>{const work=document.querySelector('.edulo-work'),diagram=document.querySelector('[data-shared-diagram]');return diagram.getBoundingClientRect().top-work.getBoundingClientRect().top+work.scrollTop;});
const fillMain=async page=>{const card=page.locator('[data-diagram-card]');for(let i=0;i<chain.length;i++){await card.locator('[data-token="'+chain[i]+'"]').tap();await card.locator('[data-slot="basic:'+i+'"]').tap();}};

let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require(path.join(require('node:os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')));}
require(path.join(dir,'build.cjs'));const html=fs.readFileSync(path.join(dir,'widget.html'),'utf8');const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html;charset=utf-8');res.end(html);});
(async()=>{let browser;try{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:920,height:900},hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.locator('[data-navigate=diagram]:visible').click();await page.locator('[data-slot="basic:0"]').waitFor();await page.addScriptTag({content:fs.readFileSync(path.join(dir,'learning.js'),'utf8')});
 assert.deepEqual(await page.evaluate(()=>{const host=document.createElement('div');document.body.append(host);const learning=createRocketLearning(host);const result=learning.getProgress();learning.destroy();host.remove();return result;}),{cloze:{earned:0,total:6},diagram:{earned:0,total:12}},'progress uses active exercise sizes');
 assert.deepEqual(await page.evaluate(saved=>{const host=document.createElement('div');document.body.append(host);const learning=createRocketLearning(host,{state:saved});const result=learning.getProgress();learning.destroy();host.remove();return result;},migrated),{cloze:{earned:6,total:6},diagram:{earned:12,total:12}},'historical V2 credits remain reflected in active diagram score');
 const card=page.locator('[data-diagram-card]');assert.equal(await page.locator('[data-shared-diagram]').count(),1);assert.equal(await card.locator('[data-slot]').count(),11);assert.equal(await page.locator('[data-branch]').count(),0);assert.equal(await page.locator('[data-flow-branch]').count(),0);
 assert.deepEqual(await card.locator('[data-flow-index]').evaluateAll(nodes=>nodes.map(e=>+e.dataset.bandHeight)),Array(6).fill(66),'main route starts with equal full-width arrows');assert.equal(await card.locator('[data-branch-label]').count(),0,'no answer labels in empty diagram');
 assert.deepEqual(await card.locator('[data-flow-index]').evaluateAll(nodes=>nodes.map(e=>e.getAttribute('fill'))),Array(6).fill('#b6c9d6'),'all unanswered main arrows are neutral');
 
 await card.locator('[data-shared-diagram]').screenshot({path:path.join(__dirname,'artifacts','diagram-empty-920.png')});
 await card.locator('[data-token="Flasche"]').tap();await card.locator('[data-slot="basic:5"]').tap();await card.locator('[data-token="Licht"]').tap();await card.locator('[data-slot="basic:0"]').tap();await card.locator('[data-shared-diagram]').screenshot({path:path.join(__dirname,'artifacts','diagram-partial-920.png')});
 assert.deepEqual(await card.locator('[data-kind="device"][data-token]').evaluateAll(nodes=>nodes.map(e=>e.dataset.token)),['Muskel','Luftpumpe','Flasche']);
 assert.equal(await card.locator('[data-flow-index="0"]').getAttribute('fill'),'#f5cf50','a chosen form colors only its own arrow');assert.equal(await card.locator('[data-flow-index="2"]').getAttribute('fill'),'#b6c9d6');
 assert.equal(await card.locator('[data-token="kinetische Energie"]').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(108, 209, 160)');
 await page.evaluate(()=>{window.diagramBefore=document.querySelector('[data-shared-diagram]');window.mainArrowsBefore=[...document.querySelectorAll('[data-flow-index]')];window.slotsBefore=[...document.querySelectorAll('[data-slot]')];window.slotPositionsBefore=window.slotsBefore.map(e=>({left:e.style.left,top:e.style.top,width:e.style.width}));});
 assert.equal(await card.locator('[data-flow-branch]').count(),0,'partial draft reveals no branches');
 await fillMain(page);
 assert.equal(await card.locator('[data-branch]').count(),0,'even complete unverified draft hides side targets');
 assert.deepEqual(await card.locator('[data-flow-index]').evaluateAll(nodes=>nodes.map(e=>e.getAttribute('fill'))),['#f6ae58','#6cd1a0','#f27770','#6cd1a0','#bc97eb','#6cd1a0']);
 for(const i of [5,7,9])assert.match(await card.locator('[data-slot="basic:'+i+'"]').textContent(),/Flasche/);
 const topBefore=await diagramTop(page);
 await card.locator('[data-check="basic"]').click();assert.match(await card.locator('.rocket-diagram-actions').textContent(),/Der Hauptweg ist richtig/);
 const topAfter=await diagramTop(page);assert(Math.abs(topAfter-topBefore)<1,`920px: diagram moved ${topAfter-topBefore}px after main check`);
 const identity=await page.evaluate(()=>{const diagram=document.querySelector('[data-shared-diagram]'),slots=[...document.querySelectorAll('[data-slot]')];return {sameDiagram:diagram===window.diagramBefore,sameArrows:[...document.querySelectorAll('[data-flow-index]')].every((e,i)=>e===window.mainArrowsBefore[i]),sameSlots:slots.every((e,i)=>e===window.slotsBefore[i]),samePositions:slots.every((e,i)=>e.style.left===window.slotPositionsBefore[i].left&&e.style.top===window.slotPositionsBefore[i].top&&e.style.width===window.slotPositionsBefore[i].width),inside:slots.every(e=>diagram.contains(e)),order:slots.map(e=>e.dataset.slot)};});
 assert(identity.sameDiagram,'the shared diagram DOM element must survive main check');assert(identity.sameArrows,'the very same main arrows are resized in place');assert(identity.sameSlots,'all main slot DOM elements must survive main check');assert(identity.samePositions,'main slot positions must survive main check');assert(identity.inside);assert.deepEqual(identity.order,chain.map((_,i)=>'basic:'+i));
 assert.equal(await page.locator('[data-shared-diagram]').count(),1);assert.equal(await page.locator('[data-branch]').count(),6);assert.equal(await page.locator('[data-flow-branch]').count(),6,'all connections visible before assignment');assert.equal(await card.locator('[data-check="losses"]').count(),0);
 assert.deepEqual(await card.locator('[data-flow-branch]').evaluateAll(nodes=>nodes.map(e=>e.getAttribute('fill'))),Array(6).fill('#b6c9d6'),'unassigned branches have one neutral color');
 assert.deepEqual(await card.locator('[data-flow-branch]').evaluateAll(nodes=>nodes.map(e=>e.dataset.sourceSlot)),['basic:1','basic:3','basic:5','basic:5','basic:7','basic:9'],'water and start heat have the same bottle source');
 assert.deepEqual(await card.locator('[data-flow-index]').evaluateAll(nodes=>nodes.map(e=>+e.dataset.bandHeight)),[66,60,54,38,32,26],'only step two shows energy diverted from the main route');
 const docks=await card.locator('[data-branch]').evaluateAll(nodes=>nodes.map(e=>({index:+e.dataset.branch,label:e.getAttribute('aria-label')})));assert.deepEqual(docks.map(x=>x.index),[0,1,2,3,4,5]);assert(docks[3].label.includes('Wasser'));assert(docks.filter(x=>x.label.includes('Umgebung')).length===5);
 for(let i=0;i<branches.length;i++){await card.locator('[data-token="Lageenergie"]').tap();await card.locator('[data-branch="'+i+'"]').tap();assert.equal(await card.locator('[data-flow-branch="'+i+'"]').count(),1,`incorrect branch ${i} keeps its connection visible`);assert.equal(await card.locator('[data-branch="'+i+'"]').count(),1);await card.locator('[data-token="'+branches[i]+'"]').tap();await card.locator('[data-branch="'+i+'"]').tap();assert.equal(await card.locator('[data-flow-branch="'+i+'"]').count(),1,'correct branch draws its arrow');assert.equal(await card.locator('[data-branch-label="'+i+'"]').count(),1);assert.equal(await card.locator('[data-shared-diagram]').count(),1);}
 assert.deepEqual(await card.locator('[data-flow-branch]').evaluateAll(nodes=>nodes.map(e=>e.getAttribute('fill'))),['#f27770','#f27770','#f27770','#6cd1a0','#f27770','#f27770']);
 assert.equal(await card.locator('[data-branch]').count(),0);assert.equal(await card.locator('[data-flow-branch]').count(),6);assert.match(await card.locator('.rocket-feedback').textContent(),/Alles richtig/);
 assert.deepEqual(await card.locator('[data-flow-index]').evaluateAll(nodes=>nodes.map(e=>+e.dataset.flowIndex)),[0,2,4,6,8,10]);assert.equal(await card.locator('[data-slot]').count(),11);
 const learningText=await card.textContent();assert.doesNotMatch(learningText,/Wirkungsgrad|Energiebetrag|η|\d\s*%/i);
 fs.mkdirSync(path.join(__dirname,'artifacts'),{recursive:true});await card.locator('[data-shared-diagram]').screenshot({path:path.join(__dirname,'artifacts','diagram-6branches.png')});
 const narrow=await browser.newPage({viewport:{width:390,height:844},hasTouch:true});narrow.on('pageerror',e=>errors.push(e.message));await narrow.goto('http://127.0.0.1:'+server.address().port);await narrow.locator('[data-navigate=diagram]:visible').click();await narrow.locator('[data-slot="basic:0"]').waitFor();await narrow.locator('[data-shared-diagram]').evaluate(e=>e.scrollLeft=275);await narrow.locator('[data-shared-diagram]').screenshot({path:path.join(__dirname,'artifacts','diagram-empty-390.png')});await fillMain(narrow);const narrowBefore=await diagramTop(narrow);await narrow.locator('[data-check="basic"]').click();const narrowAfter=await diagramTop(narrow);assert(Math.abs(narrowAfter-narrowBefore)<1,`390px: diagram moved ${narrowAfter-narrowBefore}px after main check`);
 const sideBoxes=await narrow.locator('[data-branch]').evaluateAll(nodes=>nodes.map(e=>({width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height,top:parseFloat(e.style.top)})));assert(sideBoxes.every(b=>b.width>=44&&b.height>=44),'all compact docks retain touch hit size');assert(sideBoxes.filter(b=>b.top===124).length===5,'five heat docks are only 32px below converter bottom');
 for(let i=0;i<branches.length;i++){await narrow.locator('[data-token="'+branches[i]+'"]').tap();await narrow.locator('[data-branch="'+i+'"]').tap();}
 await narrow.locator('[data-shared-diagram]').evaluate(e=>e.scrollLeft=275);await narrow.locator('[data-shared-diagram]').scrollIntoViewIfNeeded();await narrow.locator('[data-shared-diagram]').screenshot({path:path.join(__dirname,'artifacts','diagram-compact-390.png')});
 assert.equal(await narrow.locator('.rocket-flow-wrap').evaluate(e=>e.getBoundingClientRect().height),240,'compact diagram height');assert(await narrow.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no page overflow at390');
 assert.deepEqual(errors,[]);console.log(`PASS: shared diagram/main slots survive check; diagram position delta 920px=${topAfter-topBefore}px, 390px=${narrowAfter-narrowBefore}px; 11 touch targets, six visible connections keep unanswered fields after wrong assignment, V2 scores and branches migrated, no efficiency or energy amounts.`);
 }finally{await browser?.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
