const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),http=require('node:http'),assert=require('node:assert/strict');
let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require(path.join(require('node:os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')));}
const dir=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(dir,'widget.html'),'utf8'),suite=fs.readFileSync(path.resolve(dir,'../../../tools/edulo/tests/run.cjs'),'utf8');
const fixture=vm.runInNewContext('const exportedMethods=null;'+suite.slice(suite.indexOf('function fixture(mode)'),suite.indexOf('\nconst server ='))+';fixture');
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html;charset=utf-8');res.end(req.url==='/host'?fixture('normal'):html);});
async function enter(page,view){await page.locator('[data-navigate="'+view+'"]:visible').click();}
async function only(page,view){assert(await page.locator(view==='experiment'?'[data-page=experiment]':view==='cloze'?'[data-cloze-card]':'[data-diagram-card]').isVisible());assert.equal(await page.locator('[data-page=experiment]').isVisible(),view==='experiment');assert.equal(await page.locator('[data-cloze-card]').isVisible(),view==='cloze');assert.equal(await page.locator('[data-diagram-card]').isVisible(),view==='diagram');}
(async()=>{let browser;try{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1024,height:768},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url+'/host');
 await page.evaluate(content=>{const wrapper=document.querySelector('#contentWrapper');wrapper.style.cssText='position:absolute;top:40px;left:25px;width:974px;height:728px;overflow:hidden';const mount=document.querySelector('#mount');mount.style.width='920px';mount.innerHTML=content;for(const old of [...mount.querySelectorAll('script')]){const next=document.createElement('script');next.textContent=old.textContent;old.replaceWith(next);}},html);
 await page.locator('[data-controls]:not([disabled])').waitFor();await only(page,'experiment');assert.equal(await page.locator('.rocket-header,.model-details').count(),0);assert.equal(await page.locator('#experiment-title').textContent(),'Simulation der Wasserrakete');
 assert.match(await page.locator('[data-page=experiment] [data-section-score=cloze]').textContent(),/0 von 6 Punkte/);assert.match(await page.locator('[data-page=experiment] [data-section-score=diagram]').textContent(),/0 von 12 Punkte/);assert.equal(await page.locator('.rocket-progress').count(),0);
 const root=page.locator('[data-edulo-id=flaschenrakete]');const box=await root.boundingBox();assert.equal(Math.round(box.width),920);assert(box.y>=40&&box.y+box.height<=768,'root fits documented clipping wrapper');await page.screenshot({path:path.join(__dirname,'artifacts','pages-home-edulo.png')});
 assert(await page.locator('[data-efficiency-button]').isHidden());await page.locator('[data-energy-button]').click();assert(await page.locator('[data-efficiency-button]').isVisible());assert.equal(await page.locator('[data-legend-labels-button]').first().getAttribute('aria-pressed'),'false');await page.locator('[data-legend-labels-button]').first().click();assert.equal(await page.locator('[data-legend-labels-button]').first().getAttribute('aria-pressed'),'true');assert.equal(await page.locator('[data-efficiency-button]').getAttribute('aria-pressed'),'false');await page.locator('[data-efficiency-button]').click();assert.equal(await page.locator('[data-efficiency-button]').getAttribute('aria-pressed'),'true');await page.screenshot({path:path.join(__dirname,'artifacts','pages-home-energy-edulo.png')});
 await enter(page,'cloze');await only(page,'cloze');await page.screenshot({path:path.join(__dirname,'artifacts','pages-cloze-start-edulo.png')});assert.equal(await page.locator('.rocket-story-part').count(),5);await page.locator('[data-cloze="1"]').selectOption('kinetische Energie');await page.locator('[data-cloze-help="1"]').click();await page.locator('[data-more-help]').click();await page.locator('[data-close-help]').first().click();await page.locator('[data-check=cloze]').click();assert.match(await page.locator('[data-page=experiment] [data-section-score=cloze]').textContent(),/1 von 6 Punkte/);assert.match(await page.locator('[data-task-link] [data-section-score=diagram]').textContent(),/0 von 12 Punkte/);
 await enter(page,'experiment');await enter(page,'diagram');await only(page,'diagram');await page.screenshot({path:path.join(__dirname,'artifacts','pages-diagram-start-edulo.png')});assert.equal(await page.locator('[data-page-number]').textContent(),'3');assert.match(await page.locator('[data-task-link] [data-section-score=cloze]').textContent(),/1 von 6 Punkte/);assert.equal(await page.locator('[data-flow-branch]').count(),0);await page.locator('[data-token="Flasche"]').tap();await page.locator('[data-slot="basic:5"]').tap();await page.locator('[data-token="chemische Energie"]').tap();await page.locator('[data-slot="basic:0"]').tap();await page.locator('[data-check=basic]').click();assert.match(await page.locator('[data-page=experiment] [data-section-score=diagram]').textContent(),/1 von 12 Punkte/);await page.locator('[data-shared-diagram]').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(__dirname,'artifacts','pages-diagram-edulo.png')});
 await enter(page,'experiment');await enter(page,'cloze');assert.equal(await page.locator('[data-cloze="1"]').inputValue(),'kinetische Energie');await page.locator('[data-cloze-help="1"]').click();assert.match(await page.locator('.rocket-hint-stage').textContent(),/Hinweis 2 von 3/);await page.locator('[data-close-help]').first().click();await page.screenshot({path:path.join(__dirname,'artifacts','pages-cloze-edulo.png')});
 await enter(page,'experiment');await enter(page,'diagram');assert.match(await page.locator('[data-slot="basic:5"]').textContent(),/Flasche/);
 // Resize only the host container: no browser resize event.
 await page.evaluate(()=>{document.querySelector('#contentWrapper').style.height='360px';document.querySelector('#mount').style.width='390px';});await page.waitForFunction(()=>document.querySelector('[data-edulo-id=flaschenrakete]').getBoundingClientRect().height<=352);const small=await root.boundingBox();assert(small.width<=390&&small.y+small.height<=400);await enter(page,'experiment');await page.screenshot({path:path.join(__dirname,'artifacts','pages-small-host.png')});
 await page.goto(url+'/widget');await page.setViewportSize({width:390,height:844});await page.locator('[data-controls]:not([disabled])').waitFor();await only(page,'experiment');await page.locator('[data-energy-button]').click();await page.locator('[data-efficiency-button]').click();await page.locator('[data-legend-labels-button]').first().click();await enter(page,'cloze');await page.locator('[data-cloze="0"]').selectOption('chemische Energie');await enter(page,'experiment');await enter(page,'diagram');await page.locator('[data-token="Flasche"]').tap();await page.locator('[data-slot="basic:5"]').tap();await page.waitForTimeout(400);await page.reload();await page.locator('[data-controls]:not([disabled])').waitFor();assert.equal(await page.locator('[data-efficiency-button]').getAttribute('aria-pressed'),'true','efficiency option persists after reload');assert.equal(await page.locator('[data-energy-button]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('[data-legend-labels-button]').first().getAttribute('aria-pressed'),'true','legend words persist');await enter(page,'cloze');assert.equal(await page.locator('[data-cloze="0"]').inputValue(),'chemische Energie');await page.screenshot({path:path.join(__dirname,'artifacts','pages-cloze-390.png')});await enter(page,'experiment');await enter(page,'diagram');assert.match(await page.locator('[data-slot="basic:5"]').textContent(),/Flasche/);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 assert.deepEqual(errors,[]);console.log('PASS: three exclusive views; documented 920px widget in 974x728 clipped host at1024x768; preserved answers/hints/diagram across navigation and reload; container-only resize to390x360; no header/model note, branches hidden before main verification.');
 }finally{await browser?.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
