const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
let chromium;
try{({chromium}=require('playwright'));}catch{({chromium}=require(path.join(require('node:os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')));}
const source=fs.readFileSync(path.join(__dirname,'..','simulation.js'),'utf8');
const close=(a,b)=>Math.abs(a-b)<1e-5;
(async()=>{
  const browser=await chromium.launch({channel:'msedge',headless:true});
  try{
    const page=await browser.newPage({viewport:{width:920,height:768}});
    const errors=[];page.on('pageerror',error=>errors.push(error.message));
    await page.clock.install();
    await page.setContent('<div id="scene"></div>');
    await page.addScriptTag({content:source});
    await page.evaluate(()=>{window.sim=createRocketSimulation(document.querySelector('#scene'),{energyVisible:true});});
    const sample=()=>page.evaluate(()=>{
      const state=sim.getState(), packets=[...document.querySelectorAll('[data-packet-id]')];
      return {...state,areas:packets.map(node=>Number(node.querySelector('rect').getAttribute('width'))**2),lossAreas:[...document.querySelectorAll('[data-loss-id]')].map(node=>({id:node.dataset.lossId,area:Number(node.querySelector('rect').getAttribute('width'))**2}))};
    });
    const balanced=s=>{
      const total=s.packets.reduce((v,p)=>v+p.amount,0)+s.losses.reduce((v,l)=>v+l.amount,0);
      assert(close(total,5),`energy balance ${total}`);
      s.packets.forEach((p,i)=>assert(close(s.areas[i]/784,p.amount),`packet ${i} area`));
      s.losses.filter(l=>l.amount>0).forEach(l=>assert(close(s.lossAreas.find(a=>a.id===l.id).area/784,l.amount),`loss ${l.id} area`));
    };
    let s=await sample();assert.equal(s.efficiencyVisible,false);balanced(s);
    assert.equal(s.legendLabelsVisible,false);
    assert.equal(await page.locator('[data-legend-labels]:visible').count(),0);
    for(const button of await page.locator('[data-legend-labels-button]').all())await button.click();
    assert.equal((await sample()).legendLabelsVisible,true);
    assert.equal(await page.locator('[data-legend-labels]:visible').count(),4);
    for(const button of await page.locator('[data-legend-labels-button]').all())await button.click();
    assert.equal(await page.locator('[data-legend-labels]:visible').count(),0);
    assert.equal(await page.locator('[data-efficiency-button]').textContent(),'Wirkungsgrade einblenden');
    await page.locator('[data-efficiency-button]').click();
    s=await sample();assert.equal(s.efficiencyVisible,true);balanced(s);
    await page.evaluate(()=>{for(let i=0;i<5;i++)document.querySelector('[data-pump-button]').click();});
    const sizes=[];
    for(const ms of [32,80,460,5528]){await page.clock.runFor(ms);const current=await sample();balanced(current);sizes.push(Math.sqrt(current.areas[0]));}
    assert(sizes[0]>sizes[1]&&sizes[1]>sizes[2]&&sizes[2]>sizes[3],'successive conversions shrink the actual square cumulatively');
    s=await sample();assert.equal(s.phase,'launching');assert.equal(s.strokes,5);balanced(s);
    assert(s.losses.filter(l=>l.id.endsWith(':muscle')&&l.amount>0).length===5);
    assert(s.losses.filter(l=>l.id.endsWith(':pump')&&l.amount>0).length===5);
    const advance=async target=>{const current=(await sample()).flightElapsed;await page.clock.runFor(Math.max(1,Math.ceil(target-current)));};
    await advance(s.waterExitAt-35);
    s=await sample();balanced(s);assert.equal(s.packets[4].form,'thermal');
    assert.equal(s.losses.find(l=>l.id==='4:start').amount,0);
    await advance(s.waterExitAt+35);
    s=await sample();balanced(s);assert.equal(s.packets[4].form,'kinetic','water becomes kinetic at outlet');
    assert(s.losses.find(l=>l.id==='4:start').amount>0,'water splits into green kinetic packet and red ambient packet');
    const waterLoss=await page.locator('[data-loss-id="4:start"]').getAttribute('transform');
    const [lossX,lossY]=waterLoss.match(/translate\(([^ ]+) ([^)]+)\)/).slice(1).map(Number);
    const nozzle=await page.evaluate(()=>{
      const y=Number(document.querySelector('[data-bottle-position]').getAttribute('transform').match(/translate\(568 ([^)]+)\)/)[1]);
      return y+76;
    });
    assert(s.packets[4].y>=nozzle,'packet has reached the nozzle');
    assert(Math.abs(lossX-s.packets[4].x)<25&&Math.abs(lossY-nozzle)<12,'red share leaves at the actual nozzle');
    const beforeToggle=s.losses.map(l=>l.amount);
    await page.evaluate(()=>sim.setEfficiencyVisible(false));
    assert((await sample()).losses.every(l=>l.amount===0));assert((await sample()).areas.every(area=>close(area,784)),'OFF keeps all main squares at original area');
    await page.evaluate(()=>sim.setEfficiencyVisible(true));
    s=await sample();balanced(s);assert.deepEqual(s.losses.map(l=>l.amount),beforeToggle,'midflight toggle is idempotent');
    await page.screenshot({path:path.join(__dirname,'artifacts','simulation-efficiency-nozzle.png')});
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:path.join(__dirname,'artifacts','simulation-efficiency-nozzle-390.png')});
    await page.setViewportSize({width:920,height:768});
    await advance(680);
    s=await sample();balanced(s);assert.equal(s.packets[4].form,'thermal','ground impact heats the surroundings');
    const groundY=s.packets[4].y;
    const beforeAscent=(await sample()).areas[3];await advance(1600);
    s=await sample();balanced(s);assert(s.areas[3]<beforeAscent,'ascent reduction persists');assert(s.packets[4].y<groundY-5,'water heat moves away from the ground');
    const beforeFall=s.areas[0];await advance(4850);
    s=await sample();balanced(s);assert.equal(s.phase,'landed');assert(s.areas[0]<beforeFall,'fall reduction persists through landing');
    assert(s.packets.slice(0,4).every(p=>p.form==='thermal'),'bottle heat moves outside the bottle');
    assert(s.losses.filter(l=>l.amount>0).every(l=>l.visible),'emitted energy remains represented');
    for(const button of await page.locator('[data-legend-labels-button]').all())await button.click();
    assert.equal(await page.locator('[data-legend-labels]:visible').count(),4);
    const endOverlap=await page.evaluate(()=>{
      const legend=document.querySelector('[data-energy-legend]').getBoundingClientRect();
      return [...document.querySelectorAll('[data-packet-id]')].some(node=>{
        const p=node.getBoundingClientRect();
        return p.left<legend.right&&p.right>legend.left&&p.top<legend.bottom&&p.bottom>legend.top;
      });
    });
    await page.screenshot({path:path.join(__dirname,'artifacts','simulation-end-labels-920.png')});
    assert.equal(endOverlap,false,'expanded legend does not cover thermal packets');
    const prior=s.losses.map(l=>l.amount);
    await page.evaluate(()=>sim.setEfficiencyVisible(false));
    s=await sample();balanced(s);assert(s.losses.every(l=>l.amount===0));
    await page.evaluate(()=>sim.setEfficiencyVisible(true));
    s=await sample();balanced(s);assert.deepEqual(s.losses.map(l=>l.amount),prior,'toggle does not double subtract');
    await page.evaluate(()=>sim.reset());
    s=await sample();balanced(s);assert.equal(s.phase,'ready');assert(s.losses.every(l=>l.amount===0));
    await page.evaluate(()=>{for(let i=0;i<5;i++)document.querySelector('[data-pump-button]').click();});
    await page.clock.runFor(6100);
    s=await sample();balanced(s);assert.equal(s.strokes,5);
    assert(s.losses.filter(l=>l.id.endsWith(':muscle')&&l.amount>0).length===5,'second launch starts with exactly five muscle releases');
    await page.evaluate(()=>sim.reset());
    await page.locator('[data-pump-button]').click();
    await page.clock.runFor(1180);
    const before=await page.locator('[data-loss-id="0:pump"]').getAttribute('transform');
    await page.clock.runFor(45);
    const after=await page.locator('[data-loss-id="0:pump"]').getAttribute('transform');
    const xy=t=>t.match(/translate\(([^ ]+) ([^)]+)\)/).slice(1).map(Number);
    assert(Math.hypot(...xy(after).map((v,i)=>v-xy(before)[i]))<35,'completed stroke does not teleport its heat release');
    await page.clock.runFor(575);
    const mid=await page.locator('[data-loss-id="0:pump"]').getAttribute('transform');
    assert(Math.hypot(...xy(mid).map((v,i)=>v-xy(after)[i]))>2,'single-stroke heat keeps moving in ready phase');
    await page.clock.runFor(300);
    const settled=await page.locator('[data-loss-id="0:pump"]').getAttribute('transform');
    assert(Math.hypot(...xy(settled).map((v,i)=>v-xy(mid)[i]))>0,'heat reaches the environment');
    assert.equal((await sample()).animationActive,true,'heat keeps dispersing rather than parking');
    await page.clock.runFor(300);
    assert.notEqual(await page.locator('[data-loss-id="0:pump"]').getAttribute('transform'),settled,'heat continues moving');
    await page.evaluate(()=>{sim.reset();sim.setEfficiencyVisible(false);document.querySelector('[data-pump-button]').click();});
    await page.clock.runFor(1300);
    assert.equal((await sample()).animationActive,false);
    await page.evaluate(()=>sim.setEfficiencyVisible(true));
    assert.equal((await sample()).animationActive,true,'enabling efficiency resumes a pending heat animation');
    await page.clock.runFor(800);
    assert.equal((await sample()).animationActive,true);
    assert.equal(await page.locator('[data-packet-id]').count(),5);
    assert.equal(await page.locator('[data-loss-id]').count(),25);
    assert.deepEqual(errors,[]);
    console.log('PASS: model balance and square areas; nozzle split, ground and bottle heat release; toggles and reset.');
  }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});

